### PR TITLE
Implementing Associations between objects

### PR DESCRIPTION
**Pull request by youmari**
## In this branch I implemented the following : 
- Create one-to-many relationships between classroom and student 
- Create many-to-many relationships between person and book classes through rental  class

### CODE REVIEW

**Review by omar-labana — CHANGES_REQUESTED** [review]
Hi @youmari, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀
Very neat README file and linters are correctly passing. ✔️
## Required Changes ♻️
There seem to be some unpushed commits, I can't find the classroom module and its associations since there are only three file changes, kindly make sure to:
- - [x] Create the `Classroom` class.
- - [x] Make sure the has-many / belongs-to relationships exists between Classroom and Student.
- - [x] Set up correct associations between `Book` and `Person` through rentals, since there is no logic to add/update this relationship.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by er-contreras — APPROVED** [review]
Hi @youmari, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- Well done!

Felix

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by youmari** [comment]
> Hi @youmari,
> 
> Excellent work so far! 👌 You have implemented almost all the required features. ✔️ There are some cases that you need to adjust but you are almost done! 😀 Very neat README file and linters are correctly passing. ✔️
> 
> ## Required Changes ♻️
> There seem to be some unpushed commits, I can't find the classroom module and its associations since there are only three file changes, kindly make sure to:
> 
> * * [x]  Create the `Classroom` class.
> * * [x]  Make sure the has-many / belongs-to relationships exists between Classroom and Student.
> * * [x]  Set up correct associations between `Book` and `Person` through rentals, since there is no logic to add/update this relationship.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@omar-labana what do you mean by there is no logic to add/update?

**Comment by omar-labana** [comment]
> > Hi @youmari,
> > Excellent work so far! ok_hand You have implemented almost all the required features. heavy_check_mark There are some cases that you need to adjust but you are almost done! grinning Very neat README file and linters are correctly passing. heavy_check_mark
> > ## Required Changes recycle
> > There seem to be some unpushed commits, I can't find the classroom module and its associations since there are only three file changes, kindly make sure to:
> > 
> > * * [x]   Create the `Classroom` class.
> > * * [x]   Make sure the has-many / belongs-to relationships exists between Classroom and Student.
> > * * [x]   Set up correct associations between `Book` and `Person` through rentals, since there is no logic to add/update this relationship.
> > 
> > ## Optional suggestions
> > _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> > Cheers and Happy coding!clapclapclap
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> 
> @omar-labana what do you mean by there is no logic to add/update?

@youmari the method responsible for adding rentals in the book class is missing....

**Comment by omar-labana** [comment]
@youmari https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship

**Comment by youmari** [comment]
> @youmari https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship

But there is no method in the documentation that you sent? @omar-labana

**Comment by omar-labana** [comment]
@youmari check add_animal in the owner class, Both ways relationships

**Pull request merged**
